- name: Stopping Gitlab
  become: true
  ignore_errors: true
  community.docker.docker_compose:
    project_src: "{{ gitlab_directory }}"
    stopped: true

- name: Delete nginx conf
  ansible.builtin.import_tasks:
    file: utilities/delete_nginx_conf.yml
  vars:
    label: "gitlab"

- name: Remove backup cron job
  become: true
  ansible.builtin.cron:
    name: "Gitlab backup"
    state: absent