- name: Create Sonarqube directory
  become: true
  file:
    path: "{{ sonarqube_directory }}"
    state: directory
    mode: '0770'

- name: Create required directories
  become: true
  block:
    - file:
        path: "{{ item }}"
        state: directory
        mode: '0770'
        owner: 1000
        group: 1000
      loop:
        - "{{ sonarqube_directory }}/data"
        - "{{ sonarqube_directory }}/extensions"
        - "{{ sonarqube_directory }}/logs"
    - file:
        path: "{{ item }}"
        state: directory
        mode: '0770'
        owner: 999
        group: 999
      loop:
        - "{{ sonarqube_directory }}/postgresql"
        - "{{ sonarqube_directory }}/postgresql_data"


- name: Retrieve database password
  ansible.builtin.import_tasks:
    file: utilities/read_secret.yml
  vars:
    service_directory: "{{ sonarqube_directory }}"
    secret_name: "db-password.txt"
    create_if_missing: True
    output_var: "db_password"


- name: Set vm.max_map_count
  become: true
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: 262144
    sysctl_set: yes


- name: Start container
  ansible.builtin.import_tasks:
    file: utilities/start_container.yml
  vars:
    docker_compose_src_path: "docker-compose.yml.j2"
    service_directory: "{{ sonarqube_directory }}"


- name: Copy nginx configuration
  ansible.builtin.import_tasks:
    file: utilities/add_nginx_conf.yml
  vars:
    conf_src_path: "nginx.conf.j2"
    label: "sonarqube"


- name: Plan backup
  ansible.builtin.import_tasks:
    file: utilities/plan_backup.yml
  vars:
    script_src_path: "backup.sh.j2"
    service_directory: "{{ sonarqube_directory }}"
    cron_name: "Sonarqube backup"