- name: Create Sonarqube directory
  become: true
  file:
    path: "{{ sonarqube_directory }}"
    state: directory
    mode: '0770'

- name: Create required directories
  become: true
  block:
    - file:
        path: "{{ item }}"
        state: directory
        mode: '0770'
        owner: 1000
        group: 1000
      loop:
        - "{{ sonarqube_directory }}/data"
        - "{{ sonarqube_directory }}/extensions"
        - "{{ sonarqube_directory }}/logs"
        - "{{ sonarqube_directory }}/.secrets"
    - file:
        path: "{{ item }}"
        state: directory
        mode: '0770'
        owner: 999
        group: 999
      loop:
        - "{{ sonarqube_directory }}/postgresql"
        - "{{ sonarqube_directory }}/postgresql_data"

- name: Retreive database password
  become: true
  block:
    - name: Check if password exists
      stat:
        path: "{{ sonarqube_directory }}/.secrets/db-password.txt"
      register: db_password_file
    
    - name: Generate password
      when: not db_password_file.stat.exists
      copy:
        dest: "{{ sonarqube_directory }}/.secrets/db-password.txt"
        content: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits') }}"
    
    - name: Read password
      block:
        - slurp:
            src: "{{ sonarqube_directory }}/.secrets/db-password.txt"
          register: db_password_slurp
        - set_fact:
            db_password: "{{ db_password_slurp.content | b64decode }}"

- name: Set vm.max_map_count
  become: true
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: 262144
    sysctl_set: yes

- name: Copy docker-compose
  become: true
  template:
    src: docker-compose.yml.j2
    dest: "{{ sonarqube_directory }}/docker-compose.yml"
    owner: root
    mode: '0700'

- name: Docker compose up
  become: true
  community.docker.docker_compose:
    project_src: "{{ sonarqube_directory }}"
    remove_orphans: true

  
- name: Copy nginx configuration
  become: true
  block:
    - template:
        src: nginx.conf.j2
        dest: "{{ nginx_directory }}/includes/sonarqube.conf"
        owner: root
        mode: '0700'
      register: nginx_conf
    - ansible.builtin.set_fact:
        when: nginx_conf.changed
        should_restart_nginx: true


- name: Copy backup script
  become: true
  template:
    src: backup.sh.j2
    dest: "{{ sonarqube_directory }}/backup.sh"
    mode: '0770'

- name: Backup cron
  become: true
  ansible.builtin.cron:
    name: Sonarqube backup
    weekday: "{{ backup_weekday }}"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    user: root
    job: "{{ sonarqube_directory }}/backup.sh"