- name: Stopping Sonarqube
  become: true
  ignore_errors: true
  community.docker.docker_compose:
    project_src: "{{ sonarqube_directory }}"
    stopped: true

- name: Delete nginx conf
  ansible.builtin.import_tasks:
    file: utilities/delete_nginx_conf.yml
  vars:
    label: "sonarqube"

- name: Remove backup cron job
  become: true
  ansible.builtin.cron:
    name: "Sonarqube backup"
    state: absent