- name: "CAS setup"
  hosts: cas-server

  pre_tasks:
    - name: Install Docker
      import_role:
        name: docker


  tasks:
    - name: Starting services
      include_role:
        name: "{{ service_item.key }}"
        tasks_from: "{{ 'main' if service_item.value else 'stop' }}"
      loop: "{{ install | dict2items }}"
      loop_control:
        loop_var: service_item


  post_tasks:
    - name: Start nginx
      import_role:
        name: nginx
        tasks_from: main

    - name: Setup dashboard
      import_role:
        name: dashboard
        tasks_from: standard

    - name: Everything is ok
      debug:
        msg: "Everything looks fine. Visit {{schema}}://{{ domain }}"