- name: Create Mattermost directory
  become: true
  file:
    path: "{{ mattermost_directory }}"
    owner: 2000
    group: 2000
    state: directory
    mode: '0770'

- name: Create required directories
  become: true
  file:
    path: "{{ item }}"
    owner: 2000
    group: 2000
    state: directory
    mode: '0770'
  loop:
    - "{{ mattermost_directory }}/config"
    - "{{ mattermost_directory }}/data"
    - "{{ mattermost_directory }}/logs"
    - "{{ mattermost_directory }}/plugins"
    - "{{ mattermost_directory }}/bleve-indexes"


- name: Retrieve database password
  ansible.builtin.import_tasks:
    file: utilities/read_secret.yml
  vars:
    service_directory: "{{ mattermost_directory }}"
    secret_name: "db-password.txt"
    create_if_missing: True
    output_var: "db_password"


- name: Start container
  ansible.builtin.import_tasks:
    file: utilities/start_container.yml
  vars:
    docker_compose_src_path: "docker-compose.yml.j2"
    service_directory: "{{ mattermost_directory }}"


- name: Copy nginx configuration
  ansible.builtin.import_tasks:
    file: utilities/add_nginx_conf.yml
  vars:
    conf_src_path: "nginx.conf.j2"
    label: "mattermost"

  
- name: Plan backup
  ansible.builtin.import_tasks:
    file: utilities/plan_backup.yml
  vars:
    script_src_path: "backup.sh.j2"
    service_directory: "{{ mattermost_directory }}"
    cron_name: "Mattermost backup"