- name: Retreive Gitlab SSO tokens
  become: true
  block:
    - name: Client id
      block:
        - slurp:
            src: "{{ taiga_directory }}/.secrets/gitlab_sso_client.txt"
          failed_when: false
          register: slurp_res
        - set_fact:
            oauth_client: "{{ slurp_res.content | default('') | b64decode }}"
            
    - name: Secret
      block:
        - slurp:
            src: "{{ taiga_directory }}/.secrets/gitlab_sso_secret.txt"
          failed_when: false
          register: slurp_res
        - set_fact:
            oauth_secret: "{{ slurp_res.content | default('') | b64decode }}"


- name: Create OAuth tokens
  when: (oauth_secret == '') or (oauth_client == '')
  block:
    - name: Create Gitlab OAuth application
      ansible.builtin.uri:
        url: "{{ schema }}://{{ domain }}{{ gitlab_path }}/api/v4/applications"
        method: POST
        headers:
          PRIVATE-TOKEN: "{{ gitlab_access_token }}"
        body_format: json
        body:
          name: "Taiga"
          redirect_uri: "{{ schema }}://{{ domain }}{{ taiga_path }}/login"
          scopes: "read_user"
        status_code: 201
      register: gitlab_oauth

    - name: Save tokens
      become: true
      block:
        - name: Client id
          copy:
            dest: "{{ taiga_directory }}/.secrets/gitlab_sso_client.txt"
            content: "{{ gitlab_oauth.json.application_id }}"
        - name: Secret
          copy:
            dest: "{{ taiga_directory }}/.secrets/gitlab_sso_secret.txt"
            content: "{{ gitlab_oauth.json.secret }}"


- name: Restart Taiga
  import_role:
    name: taiga
