- name: Create Jenkins directory
  become: true
  file:
    path: "{{ jenkins_directory }}"
    owner: 1000
    group: 1000
    state: directory
    mode: '0770'

- name: Create required directories
  become: true
  file:
    path: "{{ item }}"
    owner: 1000
    group: 1000
    state: directory
    mode: '0770'
  loop:
    - "{{ jenkins_directory }}/home"
    - "{{ jenkins_directory }}/certs"


- name: Copy custom Jenkins Dockerfile
  become: true
  copy:
    src: Dockerfile
    dest: "{{ jenkins_directory }}/Dockerfile"
    owner: root
    mode: '0700'

- name: Build custom Jenkins
  become: true
  community.docker.docker_image:
    build:
      path: "{{ jenkins_directory }}"
    name: cas-server/jenkins
    source: build

- name: Start container
  ansible.builtin.import_tasks:
    file: utilities/start_container.yml
  vars:
    docker_compose_src_path: "docker-compose.yml.j2"
    service_directory: "{{ jenkins_directory }}"


- name: Copy nginx configuration
  ansible.builtin.import_tasks:
    file: utilities/add_nginx_conf.yml
  vars:
    conf_src_path: "nginx.conf.j2"
    label: "jenkins"

  
- name: Plan backup
  ansible.builtin.import_tasks:
    file: utilities/plan_backup.yml
  vars:
    script_src_path: "backup.sh.j2"
    service_directory: "{{ jenkins_directory }}"
    cron_name: "Jenkins backup"