- name: Create root directory
  become: true
  file:
    path: "{{ taiga_directory }}"
    state: directory
    mode: '0770'

- name: Create required directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ taiga_directory }}/db-data"
    - "{{ taiga_directory }}/media-data"


- name: Retrieve passwords
  block:
    - name: Database/RabbitMQ password
      ansible.builtin.import_tasks:
        file: utilities/read_secret.yml
      vars:
        service_directory: "{{ taiga_directory }}"
        secret_name: "password.txt"
        create_if_missing: True
        output_var: "password"

    - name: Taiga secret
      ansible.builtin.import_tasks:
        file: utilities/read_secret.yml
      vars:
        service_directory: "{{ taiga_directory }}"
        secret_name: "secret.txt"
        create_if_missing: True
        output_var: "secret"


- name: Retreive Gitlab SSO tokens
  become: true
  block:
    - name: Client id
      ansible.builtin.import_tasks:
        file: utilities/read_secret.yml
      vars:
        service_directory: "{{ taiga_directory }}"
        secret_name: "gitlab_sso_client.txt"
        create_if_missing: False
        output_var: "taiga_gitlab_clientid"

    - name: Secret
      block:
        - name: "Read SSO secret"
          ansible.builtin.import_tasks:
            file: utilities/read_secret.yml
          vars:
            service_directory: "{{ taiga_directory }}"
            secret_name: "gitlab_sso_secret.txt"
            create_if_missing: False
            output_var: "taiga_gitlab_clientsecret"
        - name: "Escape SSO secret"
          set_fact:
            taiga_gitlab_clientsecret: "{{ taiga_gitlab_clientsecret | replace('$', '$$') }}"


- name: Copy internal nginx configuration
  become: true
  template:
    src: taiga.conf
    dest: "{{ taiga_directory }}/taiga.conf"
    mode: '0770'


- name: Start container
  ansible.builtin.import_tasks:
    file: utilities/start_container.yml
  vars:
    docker_compose_src_path: "docker-compose.yml.j2"
    service_directory: "{{ taiga_directory }}"


- name: Copy nginx configuration
  ansible.builtin.import_tasks:
    file: utilities/add_nginx_conf.yml
  vars:
    conf_src_path: "nginx.conf.j2"
    label: "taiga"


- name: Plan backup
  ansible.builtin.import_tasks:
    file: utilities/plan_backup.yml
  vars:
    script_src_path: "backup.sh.j2"
    service_directory: "{{ taiga_directory }}"
    cron_name: "Taiga backup"