- name: Install required packages
  become: true
  apt:
    pkg:
    - ca-certificates
    - gnupg
    - lsb-release
    - python3
    - python3-pip
    state: latest
    update_cache: true

- name: Add Docker GPG key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/{{ distro }}/gpg"
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ distro }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker-ce and docker compose
  become: true
  apt:
    name: 
      - docker-ce
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Install Docker SDK for Python
  become: true
  pip:
    name: 
      - docker
      - docker-compose

- name: Create network for CAS containers
  become: true
  community.docker.docker_network:
    name: "{{ docker_network }}"