- name: Create nginx directory
  become: true
  file:
    path: "{{ nginx_directory }}"
    state: directory
    mode: '0770'

- name: Reset includes directory
  become: true
  block:
    - name: Delete includes
      file:
        state: absent
        path: "{{ nginx_directory }}/includes"

    - name: Create includes
      file:
        path: "{{ nginx_directory }}/includes"
        state: directory
        mode: '0770'


- name: Create public directory
  become: true
  file:
    path: "{{ nginx_directory }}/public"
    state: directory
    mode: '0775'


- name: Create secrets directory
  become: true
  file:
    path: "{{ nginx_directory }}/.secrets"
    state: directory
    mode: '0700'


- name: Copy dashboard file
  become: true
  template:
    src: dashboard.html.j2
    dest: "{{ nginx_directory }}/public/index.html"
    mode: '0775'